apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spare
  namespace: tbd
  labels:
    team: tbd
spec:
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    requests:
      cpu: 50m
  replicas:
    min: 1
  prometheus:
    enabled: true
    path: /metrics
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spare-v1
    - name: KAFKA_RESET_POLICY
      value: earliest
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
