apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spare
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 196Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        diskAutoresize: true
        pointInTimeRecovery: true
        name: spare
        databases:
          - name: spare
            envVarPrefix: DATABASE
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spare-v1
  - name: KAFKA_RESET_POLICY
    value: earliest
