apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spare
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi
  replicas:
    min: 1
    max: 6
    scalingStrategy:
      kafka:
        topic: tbd.rapid.v1
        consumerGroup: tbd-spare-v1
        threshold: 200

  kafka:
    pool: nav-prod
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        pointInTimeRecovery: true
        name: spare2
        tier: db-custom-1-3840
        databases:
          - name: spare
            envVarPrefix: DATABASE
            users:
              - name: helse-sparker-feriepenger
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spare-v1
  - name: KAFKA_RESET_POLICY
    value: earliest
