apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spare
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvspare
  env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
  - name: KAFKA_RAPID_TOPIC
    value: helse-rapid-v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: spare-v1
  - name: KAFKA_RESET_POLICY
    value: earliest
  - name: JDBC_URL
    value: "jdbc:postgresql://b27dbvl023.preprod.local:5432"
  - name: DB_NAME
    value: spare
  - name: VAULT_MOUNTPATH
    value: postgresql/prod-fss/
