apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spare
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 90
  kafka:
    pool: nav-prod
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvspare
  env:
  - name: KAFKA_RAPID_TOPIC
    value: htbd.rapid.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spare-v1
  - name: KAFKA_RESET_POLICY
    value: earliest
  - name: JDBC_URL
    value: "jdbc:postgresql://a01dbvl027.adeo.no:5432"
  - name: DB_NAME
    value: spare
  - name: VAULT_MOUNTPATH
    value: postgresql/prod-fss/
